version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - alpine_data:/usr/share/nginx/html

  alpine:
    image: alpine:latest
    restart: unless-stopped
    volumes:
      - alpine_data:/var/www/html
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure 
    environment:
      - MESSAGE=Hello from Alpine
      - HOSTNAME=alpine-$${HOSTNAME= -1}
    command: sh -c 'mkdir -p /var/www/html/ && echo $$MESSAGE-$$HOSTNAME > /var/www/html/index.html && tail -f /dev/null'

volumes:
  alpine_data:

